import type { Project } from "@/app/lib/projects";

export default function ProjectArtwork({ project }: { project: Project }) {
  switch (project.variant) {
    case "drift":
      return <div className="project-art art-drift" aria-hidden="true"><div className="art-window"><div className="window-top"><span /><span /><span /><b>FLIGHT REVIEW / 0042</b><i>•••</i></div><div className="flight-ui"><div className="flight-map"><div className="map-contour contour-a" /><div className="map-contour contour-b" /><div className="map-contour contour-c" /><span className="map-point">A</span><span className="map-point map-point-two">B</span><span className="map-axis">N</span></div><div className="flight-data"><span>ALTITUDE / M</span><svg viewBox="0 0 320 110"><path d="M0 80 C18 76 20 32 44 42 S67 81 88 59 111 28 133 43 151 75 169 56 192 19 211 32 229 72 250 53 272 38 287 48 304 21 320 27"/><circle cx="250" cy="53" r="4"/></svg><div className="flight-timeline"><i /><i /><i /><i /></div></div></div><div className="window-foot"><span>VIDEO SYNCED</span><span>ANOMALIES <b>03</b></span><span>02:14:08</span></div></div><span className="art-caption">MOTION / EVENT / CONTEXT</span></div>;
    case "stoneforge":
      return <div className="project-art art-stoneforge" aria-hidden="true"><div className="terrain-orb"><div /><div /><div /><div /><b>SF</b></div><span className="terrain-label terrain-label-one">SCAN / 04</span><span className="terrain-label terrain-label-two">3D RECONSTRUCTION</span><span className="terrain-coordinate">X 04.287&nbsp;&nbsp; Y 09.412</span><span className="terrain-scanline" /></div>;
    case "retail":
      return <div className="project-art art-retail" aria-hidden="true"><div className="retail-app"><div className="retail-side"><b>n.</b><i /><i /><i /><i /></div><div className="retail-main"><span className="retail-overline">OVERVIEW / WEDNESDAY 12</span><b className="retail-heading">Good morning,<br />Mithil.</b><div className="retail-stats"><div><small>IN STOCK</small><strong>248 <i>+12%</i></strong></div><div><small>NEEDS ATTENTION</small><strong>08 <i>→</i></strong></div><div><small>ON ORDER</small><strong>17 <i>+03</i></strong></div></div><div className="retail-list"><span>RECENT ORDERS</span><i /><i /><i /></div></div></div><span className="art-caption">STOCK / ORDERS / MOMENTUM</span></div>;
    case "qkd":
      return <div className="project-art art-qkd" aria-hidden="true"><div className="qkd-head"><span>TF-QKD / DETECTOR LAB</span><span>SIMULATION 06</span></div><div className="qkd-canvas"><div className="qkd-wave wave-one" /><div className="qkd-wave wave-two" /><div className="qkd-wave wave-three" /><div className="qkd-beam" /><div className="qkd-node node-a">TX</div><div className="qkd-node node-b">RX</div><div className="qkd-glow" /><span className="qkd-metric">AUROC <b>0.935</b></span><span className="qkd-distance">100 KM</span></div><div className="qkd-legend"><span>· NORMAL</span><span>· ANOMALY</span><span>· HELD-OUT</span></div><span className="art-caption">SIMULATED PULSES / 22M</span></div>;
    case "oracle":
      return <div className="project-art art-oracle" aria-hidden="true"><div className="oracle-starfield"><i /><i /><i /><i /><i /><div className="oracle-orbit" /><div className="oracle-core">?</div></div><div className="oracle-prediction"><span>SCENARIO / 04</span><b>Will the signal hold?</b><div><i>YES <strong>64%</strong></i><i>NO <strong>36%</strong></i></div></div><span className="art-caption">A SMALL TOOL FOR BIG MAYBES</span></div>;
    case "pinn":
      return <div className="project-art art-pinn" aria-hidden="true"><div className="pinn-equation">∇ · B = 0</div><div className="pinn-grid"><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /></div><div className="pinn-curl"><span>∂T / ∂t</span><b>∿</b><span>u · ∇T</span></div><span className="art-caption">COUPLED FIELD / IN PROGRESS</span></div>;
    case "jarvis":
      return <div className="project-art art-jarvis" aria-hidden="true"><div className="jarvis-orbit orbit-one"/><div className="jarvis-orbit orbit-two"/><div className="jarvis-core">J</div><div className="jarvis-terminal"><span>J.A.R.V.I.S. / SYSTEM READY</span><b>Good evening, Mithil.</b><i>› How can I help you today?</i></div><span className="art-caption">LOCAL CONTEXT / CLOUD INTELLIGENCE</span></div>;
    case "fraud":
      return <div className="project-art art-fraud" aria-hidden="true"><div className="fraud-score"><span>LIVE RISK SCORE</span><b>0.08</b><i>LOW RISK</i></div><div className="fraud-chart"><span/><span/><span/><span/><span/><span/><span/><span/><span/><span/><span/><span/></div><div className="fraud-transactions"><i/><i/><i/><i/></div><span className="art-caption">TRANSACTION SIGNALS / EXPLAINABLE AI</span></div>;
    case "kepler":
      return <div className="project-art art-kepler" aria-hidden="true"><div className="kepler-stars"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="kepler-planet"><i/></div><div className="kepler-data"><span>KOI-4878.01</span><b>0.94</b><i>PLANET CANDIDATE</i></div><span className="art-caption">KEPLER OBJECTS OF INTEREST / 01</span></div>;
    case "quantum":
      return <div className="project-art art-quantum" aria-hidden="true"><div className="quantum-mark">Q<span>F</span></div><div className="quantum-label"><b>Curiosity,<br/>in superposition.</b><span>QUANTUM COMPUTING TEAM<br/>IEEE STUDENT BRANCH / BPHC</span></div><div className="quantum-rings"><i/><i/><i/></div><span className="art-caption">LEARN / EXPLORE / CONNECT</span></div>;
    case "beijan":
      return <div className="project-art art-beijan" aria-hidden="true"><div className="beijan-sun"/><div className="beijan-wordmark">beijan<span>®</span></div><div className="beijan-line line-one"/><div className="beijan-line line-two"/><span className="beijan-caption">TECHNOLOGY FOR WHAT&apos;S NEXT</span><span className="art-caption">A STARTUP, FINDING ITS SIGNAL</span></div>;
    case "mobile":
      return <div className="project-art art-mobile" aria-hidden="true"><div className="mobile-panel"><div className="mobile-top"><b>Inventory</b><span>● HQ</span></div><div className="mobile-metric"><small>AVAILABLE STOCK</small><b>248 <i>+12%</i></b></div><div className="mobile-row"><i>◧</i><span>iPhone 16 Pro</span><b>24</b></div><div className="mobile-row"><i>◧</i><span>Galaxy S25</span><b>18</b></div><div className="mobile-row"><i>◧</i><span>Pixel 9 Pro</span><b>12</b></div><div className="mobile-order">＋ &nbsp; CREATE PURCHASE ORDER</div></div><span className="art-caption">BRANCH STOCK / HQ ORDERS</span></div>;
    case "deltarune":
      return <div className="project-art art-deltarune" aria-hidden="true"><div className="dark-world-stars"><i/><i/><i/><i/><i/><i/></div><div className="dark-world-sun"><span>✦</span></div><div className="dark-world-dialog"><span>★ &nbsp; MITHIL</span><b>A portfolio<br/>with a little<br/>more soul.</b><i>▼</i></div><div className="dark-world-heart">♥</div><span className="art-caption">A SMALL ADVENTURE / 2026</span></div>;
  }
}
